apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  name: node
  namespace: default       
spec: 
  maxReplicas: 15 
  minReplicas: 7
  scaleTargetRef: 
    apiVersion: apps/v1beta1 
    kind: Deployment 
    name: node-deployment
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 5Gi
