apiVersion: batch/v1 
kind: Job 
metadata: 
  name: node-load 
  labels: 
    app: node 
    component: load 
spec: 
  template: 
    spec: 
      containers: 
      - name: node-load 
        image: errm/ab 
        args: ["-n1000", "-c4", "fib/30"] 
      restartPolicy: OnFailure
